import os
from django.contrib import admin
from django.urls import reverse, NoReverseMatch
from django.test.utils import override_settings
from django.core.management.base import BaseCommand
from django.core.exceptions import AssertionError

def print_stacktrace(e: Exception):
    import traceback
    import sys
    tb = traceback.extract_tb(e.__traceback__)
    print("Traceback (most recent call last):", file=sys.stderr)
    for frame in tb:
        line_number = frame.lineno
        code_context = frame.line.strip() if frame.line else "Unknown"
        print(f'  File "{frame.filename}"', file=sys.stderr)
        print(f"    {line_number}: {code_context}", file=sys.stderr)
    print(f"{e.__class__.__name__}: {e}", file=sys.stderr)

class MyModel(admin.ModelAdmin):
    readonly_fields = ['foreign_key']

    def get_admin_url(self, obj):
        try:
            return reverse('admin:myapp_mymodel_change', args=[quote(obj.fk.pk)])
        except NoReverseMatch as e:
            print_stacktrace(e)
            raise AssertionError("Wrong URL generated by get_admin_url")

class MyAdminSite(admin.AdminSite):
    def has_permission(self, request):
        return True

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')

admin.site.register(MyModel, MyModel)

class Command(BaseCommand):
    help = 'Reproduce the issue'

    def handle(self, *args, **options):
        try:
            obj = MyModel()
            obj.fk = MyModel()  # Create a fake ForeignKey object
            admin_url = MyModel().get_admin_url(obj)
            if not admin_url.startswith('/custom-admin/'):
                print_stacktrace(Exception(f"Wrong URL generated: {admin_url}"))
                raise AssertionError("Wrong URL generated by get_admin_url")
        except Exception as e:
            print_stacktrace(e)
            raise
        else:
            print("Issue fixed. Exiting with code 0.")
            exit(0)

if __name__ == '__main__':
    Command().handle()
