import os
from django.contrib import admin
from django.urls import reverse, NoReverseMatch
from django.test.utils import override_settings
from django.db.models import Model
from django.core.exceptions import AssertionError

def print_stacktrace(e: Exception):
    import traceback
    import sys
    tb = traceback.extract_tb(e.__traceback__)
    print("Traceback (most recent call last):", file=sys.stderr)
    for frame in tb:
        line_number = frame.lineno
        code_context = frame.line.strip() if frame.line else "Unknown"
        print(f'  File "{frame.filename}"', file=sys.stderr)
        print(f"    {line_number}: {code_context}", file=sys.stderr)
    print(f"{e.__class__.__name__}: {e}", file=sys.stderr)

class MyModel(Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.foreign_key = None

class MyAdmin(admin.ModelAdmin):
    readonly_fields = ['foreign_key']

admin.site.register(MyModel, MyAdmin)

def get_admin_url(remote_obj):
    url_name = 'admin:%s_%s_change' % (remote_obj._meta.app_label, remote_obj._meta.model_name)
    try:
        return reverse(url_name, args=[quote(remote_obj.pk)])
    except NoReverseMatch:
        raise AssertionError("Wrong URL generated by get_admin_url")

def quote(obj):
    return str(obj)

if __name__ == '__main__':
    try:
        get_admin_url(MyModel())
    except AssertionError as e:
        print_stacktrace(e)
        exit(1)
